---
- name: Insert live system metrics into PostgreSQL
  hosts: all
  gather_facts: no
  vars_files:
    - vault.yml
  vars:
    db_host: "10.223.0.55"
    db_port: 30200
    db_name: "logger"
    db_user: "{{ db_user }}"
    db_password: "{{ db_password }}"
    cpu_table: "cpu_table"
    mem_table: "mem_table"

  roles:
    - get_cpu_load
    - get_mem_load
    - get_disk_load