---
- name: Insert live system metrics into PostgreSQL
  hosts: all
  gather_facts: no
  vars:
    db_host: "192.168.137.159"
    db_port: 30200
    db_name: "logger"
    db_user: "logger"
    db_password: "lohpidr"
    table_name: "system_metrics"

  roles:
    - get_cpu_load
