---
- name: Gather live CPU load
  shell: "awk '{print $1 / n}' n=$(nproc) /proc/loadavg"
  register: cpu_load

- name: Gather hostname
  shell: "cat /etc/hostname"
  register: hostname

- name: Gather date
  shell: "date +'%Y-%m-%d %H:%M:%S'"
  register: date

- name: Insert data into the {{ cpu_table }} table
  community.postgresql.postgresql_query:
    db: "{{ db_name }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    login_host: "{{ db_host }}"
    port: "{{ db_port }}"
    query: |
      INSERT INTO {{ cpu_table }} (hostname, load, date)
      VALUES ('{{ hostname.stdout }}', {{ cpu_load.stdout | float }}, '{{ date.stdout }}');
  delegate_to: localhost
  when: hostname.stdout is defined